### ISSUE TITLE
LedBehavior: GPIO still active after behaviors

### ISSUE THREAD

**Issue by harlem88** [edgehog-device-manager/edgehog-esp32-device#77]
If you execute one of the behaviors implemented by `LedBehavior`, the GPIO remains enabled after execution.

To reproduce it, go on Edgehog frontend page and click the identify button in check my device section.

**Comment by sorru94** [comment]
N.B. LED status depends on the hardware configuration of the board used. We can assume the LED is connected to ground through a resistor as the default behavior.
