### ISSUE TITLE
Make use of updated OTARequest and new OTAEvent interfaces

### ISSUE THREAD

**Issue by bettio** [edgehog-device-manager/edgehog-esp32-device#78]
- https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/issues/51
- https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/issues/52
- https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/issues/54
- https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/issues/55
- https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/issues/56

**Comment by harlem88** [comment]
- [ ] Handle the `operation` endpoint on OTARequest interface.
The `OTARequest` interface  introduces a new endpoint called `operation` to specify which operation is to be performed on the OTA process. The new operations are: 
      - `Update`: push an OTA update operation
      - `Cancel`: cancel an update if it can still be cancelled.

- [ ] Introduce new status/statusCodes to the OTA process:
       see: https://github.com/edgehog-device-manager/edgehog-astarte-interfaces/issues/55

- [ ] Add a progess to OTA process:
      In order to provide a better feedback let's provide intermediate progress as percentual. Such as (Downloading, 25).
